server:
  port: 8080
spring:
  datasource:
    url : jdbc:mysql://localhost:3306/goodthings?characterEncoding=utf-8
    username : root
    password : root
    driver-class-name : com.mysql.jdbc.Driver
swagger:
  enable : true
